### ISSUE TITLE
Configuration caching

### ISSUE THREAD

**Issue by jdoubleu** [helhum/typo3-config-handling#3]
Is there a reason why caching is disabled for local development configuration?

The _ConfigLoader_ code generated in [RootConfig.php:L50](https://github.com/helhum/typo3-config-handling/blob/master/src/RootConfig.php#L50) for the `AdditionalConfiguration.php` does not set the caching flag in the `populate()` function.

I checked the [ConfigLoader](https://github.com/helhum/typo3-config-handling/blob/master/src/ConfigLoader.php) and it would correctly detect file changes by modification time.
If the modification time isn't reliable in some environments I would suggest content hashing.

The ConfigLoader uses Symfony's YAML Parser which is slower than the [PECL YAML php extension](https://pecl.php.net/package/yaml) (compare https://github.com/koenpunt/yaml-php-benchmark).

**Comment by helhum** [comment]
> Is there a reason why caching is disabled for local development configuration?

The reason is, that in my tests the performance impact was detectable but acceptable in dev context.

Besides that, if not working on configuration and performance is important `typo3cms settings:dump --no-dev` can be called, which writes everything a flat PHP array for TYPO3.

No parsing is involved then.

Besides trying to squeeze out some performance for dev context, what is your main concern or use case for having an additional caching layer?

**Comment by jdoubleu** [comment]
You're right, this really only makes sense in a dev context to save a bit time.
As mentioned in this PR https://github.com/helhum/config-loader/pull/2#issuecomment-363328498 it would save me _~300ms_ for each request.

> `typo3cms settings:dump --no-dev` 

This would indeed help me for now. Thanks for the advice.

Another suggestion I have is to enable caching through an option in the `composer.json`. In the [RootConfig](https://github.com/helhum/typo3-config-handling/blob/master/src/RootConfig.php), where the code is generated, you already read from the `composer.json`.

**Comment by helhum** [comment]
With the yaml extension loaded the overhead for no cache is 3ms on my machine. I don't think there is the need to enable caching here
