### ISSUE TITLE
Settings in extensions inside extension manager are not parsed

### ISSUE THREAD

**Issue by robsonrobi** [helhum/typo3-config-handling#8]
Using helhum/typo3-config-handling all configuration gets parsed and filled inside the AdditionalConfiguration.php. When switching to the TYPO3 Backend and checking for example the values, that are used in the settings for realurl, the defaul values are shown and not the working ones inside the AdditionalConfiguration.php

Question: Is it possible to write directly into the LocalConfiguration.php ?

**Comment by helhum** [comment]
> Is it possible to write directly into the LocalConfiguration.php

No that is not possible. It isn't feasible for dev mode, as it would require to dump the settings every time you change configuration and it would not work for production settings with keeping the feature to be able to remove certain parts of the TYPO3 default configuration before applying the project configuration.

If you want to have the convenience to change configuration via UI, you can however add the [XCLASS definitions](https://github.com/helhum/TYPO3-Distribution/blob/c2cde80f248525945459458d308c3e8d9962fbb1/config/dev.settings.yaml#L5-L10) (recommended only in development), so that config options are always read from project configuration and are also written to it.

Does this help?

**Comment by robsonrobi** [comment]
Okay, i understand. Is there a chance only to write only Custom Config EXT settings into the AdditionalConfiguration ad leave the rest as it is? For example i configure EXT:realurl, ...

That would be the feature we need.

**Comment by robsonrobi** [comment]
Okay. Thanks.
